[tool.black]
line-length = 80

[tool.isort]
line_length = 80
profile = "black"
known_first_party = ["extract", "main", "repository"]

dependencies = [
    "jinja2==3.1.2",
    "pandas==2.1.3",
    "pip==23.3.1",
    "python-dotenv[cli]==1.0.0",
    "python-gitlab==4.1.1"
]
